"""add_quota

Revision ID: 04b23376b3aa
Revises: 9f7c84ef227c
Create Date: 2025-03-17 10:21:17.048568+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b23376b3aa'
down_revision: Union[str, None] = '9f7c84ef227c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column(
        'quota', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'quota')
    # ### end Alembic commands ###
